os: linux

language: node_js

node_js:
  - 12.14.0

# Safelist
branches:
  only:
    - master

cache:
  npm: true
  pip: true

# Retry install on fail to avoid failing a build on network/disk/external errors
install:
  - travis_retry npm install

jobs:
  include:
    - before_script:
        - npm i
      script:
        # - npm run test:markdown
        - npm run test:stylelint
        - npm run test:eslint
        - npm run build
